# Generated by Django 5.1.7 on 2025-06-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField()),
                ('memoria_ram', models.IntegerField(null=True)),
                ('almacenamiento', models.IntegerField(null=True)),
                ('numero_serie', models.CharField(max_length=100, null=True)),
                ('fecha_de_compra', models.DateField(null=True)),
                ('imei', models.CharField(max_length=100, null=True)),
                ('mac', models.CharField(max_length=100, null=True)),
                ('en_bodega', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Sistema_operativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
    ]
