# Generated by Django 5.1.7 on 2025-06-22 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField()),
                ('memoria_ram', models.IntegerField(null=True)),
                ('almacenamiento', models.IntegerField(null=True)),
                ('numero_serie', models.CharField(max_length=100, null=True)),
                ('fecha_de_compra', models.DateField(null=True)),
                ('imei', models.CharField(max_length=100, null=True)),
                ('mac', models.CharField(max_length=100, null=True)),
                ('en_bodega', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
                ('estado_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_anterior', to='inventario.estado_equipo')),
                ('nuevo_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_nuevo', to='inventario.estado_equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estado_equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_equipo'),
        ),
        migrations.AddField(
            model_name='modelo_equipo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_marca'),
        ),
        migrations.AddField(
            model_name='modelo_equipo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_tipo'),
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_marca')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='procesador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.procesador'),
        ),
        migrations.CreateModel(
            name='Sistema_operativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_marca')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.sistema_operativo'),
        ),
    ]
