# Generated by Django 5.1.7 on 2025-06-28 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo_historial',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo'),
        ),
        migrations.AddField(
            model_name='equipo_historial',
            name='estado_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_anterior', to='inventario.estado_equipo'),
        ),
        migrations.AddField(
            model_name='equipo_historial',
            name='nuevo_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_nuevo', to='inventario.estado_equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estado_equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_equipo'),
        ),
        migrations.AddField(
            model_name='modelo_equipo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_marca'),
        ),
        migrations.AddField(
            model_name='modelo_equipo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_tipo'),
        ),
        migrations.AddField(
            model_name='procesador',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='procesador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.procesador'),
        ),
        migrations.AddField(
            model_name='sistema_operativo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.sistema_operativo'),
        ),
    ]
