# Generated by Django 5.1.7 on 2025-03-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_tipo_equipo_rename_equipos_equipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoEquipo',
            new_name='Estado_equipo',
        ),
        migrations.RenameModel(
            old_name='ModeloEquipo',
            new_name='Modelo_equipo',
        ),
        migrations.RenameModel(
            old_name='SistemaOperativo',
            new_name='Sistema_operativo',
        ),
    ]
