# Generated by Django 5.2.3 on 2025-06-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_carga_inicial_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
