# Generated by Django 5.1.7 on 2025-03-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_estadoequipo_estado_equipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_modelo_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Tipo_equipo',
            new_name='Modelo_modelo_marca',
        ),
        migrations.RenameField(
            model_name='modelo_modelo_marca',
            old_name='nombre',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='sistema_operativo',
            name='compania',
        ),
        migrations.AddField(
            model_name='modelo_equipo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_modelo_marca'),
        ),
        migrations.AddField(
            model_name='sistema_operativo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_modelo_marca'),
        ),
        migrations.AddField(
            model_name='modelo_equipo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_modelo_tipo'),
        ),
    ]
