# Generated by Django 5.2.3 on 2025-07-01 02:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equipo_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo_historial',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo_historial',
            name='estado_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_anterior', to='inventario.estado_equipo'),
        ),
        migrations.AlterField(
            model_name='equipo_historial',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipo_historial',
            name='nuevo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nuevo_estado', to='inventario.estado_equipo'),
        ),
    ]
