# Generated by Django 5.1.7 on 2025-03-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_modelo_modelo_marca_modelo_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesador',
            name='compania',
        ),
        migrations.AddField(
            model_name='procesador',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo_marca'),
        ),
    ]
