# Generated by Django 5.2.3 on 2025-07-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_equipo_historial_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='etiqueta',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
