# Generated by Django 5.1.7 on 2025-07-03 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_equipo_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_de_compra',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
