# Generated by Django 5.1.7 on 2025-03-26 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_procesador_compania_procesador_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
                ('estado_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_anterior', to='inventario.estado_equipo')),
                ('nuevo_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_nuevo', to='inventario.estado_equipo')),
            ],
        ),
    ]
