# Generated by Django 5.1.7 on 2025-03-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_equipo_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='en_bodega',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_de_compra',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='imei',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='mac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
