from .view_detalle_mantencion import detalle_mantencion
from .view_editar_mantencion import editar_mantencion
from .view_ejecutar_mantencion import nueva_mantencion_registro
from .view_lista_mantencion import lista_mantenciones
from .view_crear_tipo_mantencion import crear_tipo_mantencion,crear_tarea
from .view_cambiar_mantencion import cambiar_mantencion
from .view_lista_tipos_mantencion import lista_tipos_mantencion
from .view_detalle_tipo_mantencion import detalle_tipo_mantencion
from .view_equipos_sin_mantencion import equipos_sin_mantencion
from .view_eliminar_mantencion import eliminar_mantencion
from .view_editar_tipo_mantencion import editar_tipo_mantencion, agregar_tarea_tipo_mantencion, eliminar_tarea_tipo_mantencion
from .AJAX_cargar_tareas_mantencion import obtener_tareas_por_tipo
from .view_lista_template_mantencion import lista_template_mantencion
from .view_eliminar_tipo_mantencion import eliminar_tipo_mantencion
from .view_contactar_mantenciones  import contactar_mantenciones