from .view_detalle_mantencion import detalle_mantencion
from .view_editar_mantencion import editar_mantencion
from .view_ejecutar_mantencion import nueva_mantencion_registro
from .view_lista_mantencion import lista_mantenciones