# Generated by Django 5.1.7 on 2025-05-14 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0008_equipo_en_bodega_equipo_fecha_de_compra_equipo_imei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(null=True)),
                ('nombre_receptor', models.CharField(max_length=100, null=True)),
                ('flag_aprobado_remuneraciones', models.BooleanField(default=None)),
                ('flag_entregado', models.BooleanField(default=False)),
                ('id_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.equipo')),
            ],
        ),
    ]
