# Generated by Django 5.2.3 on 2025-06-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(null=True)),
                ('nombre_receptor', models.CharField(max_length=100, null=True)),
                ('flag_aprobado_remuneraciones', models.BooleanField(default=None, null=True)),
                ('flag_entregado', models.BooleanField(default=False)),
                ('id_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.equipo')),
            ],
        ),
    ]
