# Generated by Django 5.1.7 on 2025-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='flag_aprobado_remuneraciones',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
