# Generated by Django 5.1.7 on 2025-07-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='nombre_receptor',
        ),
    ]
