# Generated by Django 5.1.7 on 2025-06-28 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea_realizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('realizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_tipo_mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('frecuencia_dias', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(default='Desconocido', max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='mantenciones.mantencion')),
            ],
        ),
    ]
