# Generated by Django 5.1.7 on 2025-06-29 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea_tipo_mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(default='Desconocido', max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='mantenciones.mantencion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_mantencion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_realizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('realizada', models.BooleanField(default=False)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_realizadas', to='mantenciones.registro_mantencion')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenciones.tarea_tipo_mantencion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('frecuencia_dias', models.PositiveIntegerField(default=30)),
                ('modelo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_mantencion', to='inventario.modelo_tipo')),
                ('sistema_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_mantencion_so', to='inventario.sistema_operativo')),
            ],
        ),
        migrations.AddField(
            model_name='tarea_tipo_mantencion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenciones.tipo_mantencion'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenciones.tipo_mantencion'),
        ),
    ]
