# Generated by Django 5.1.7 on 2025-06-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_mantencion',
            name='tipo',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
