# Generated by Django 5.1.7 on 2025-06-28 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
        ('mantenciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_mantencion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_mantencion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea_realizada',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_realizadas', to='mantenciones.registro_mantencion'),
        ),
        migrations.AddField(
            model_name='tarea_realizada',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenciones.tarea_tipo_mantencion'),
        ),
        migrations.AddField(
            model_name='tipo_mantencion',
            name='modelo_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_mantencion', to='inventario.modelo_tipo'),
        ),
        migrations.AddField(
            model_name='tipo_mantencion',
            name='sistema_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_mantencion_so', to='inventario.sistema_operativo'),
        ),
        migrations.AddField(
            model_name='tarea_tipo_mantencion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenciones.tipo_mantencion'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenciones.tipo_mantencion'),
        ),
    ]
