# Generated by Django 5.1.7 on 2025-06-26 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenciones', '0003_alter_tipo_mantencion_modelo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_mantencion',
            name='sistema_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_mantencion_so', to='inventario.sistema_operativo'),
        ),
        migrations.AlterField(
            model_name='tipo_mantencion',
            name='modelo_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_mantencion', to='inventario.modelo_tipo'),
        ),
    ]
