from .modelo_marca import Modelo_marca
from .equipo_historial import Equipo_historial
from .modelo_tipo import Modelo_tipo
from .modelo_equipo import Modelo_equipo
from .procesador import Procesador
from .estado_equipo import Estado_equipo
from .sistema_operativo import Sistema_operativo
from .equipo import Equipo
from .ubicacion import Ubicacion
