# Generated by Django 5.2.3 on 2025-06-22 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0001_initial'),
        ('usuarios', '0002_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametro.obra'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sala_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametro.salaventa'),
        ),
    ]
