# Generated by Django 5.2.3 on 2025-06-28 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0002_ubicacion'),
        ('usuarios', '0003_alter_usuario_obra_alter_usuario_sala_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sala_venta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametro.ubicacion'),
        ),
    ]
