# Generated by Django 5.1.7 on 2025-03-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='modelo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.modeloequipo'),
        ),
    ]
