# Generated by Django 5.1.7 on 2025-03-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_modeloequipo_equipos_modelo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='modelo_id',
            new_name='modelo',
        ),
    ]
