# Generated by Django 5.1.4 on 2025-03-18 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_rename_modelo_id_equipos_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('compania', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('compania', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='modeloequipo',
            old_name='nombre_modelo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='equipos',
            name='almacenamiento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipos',
            name='memoria_ram',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.estadoequipo'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='procesador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.procesador'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='sistema_operativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.sistemaoperativo'),
        ),
    ]
